services:
  app:
    develop:
      watch:
        - action: sync+restart
          path: ./app/app.py
          target: /app/app.py
        - action: rebuild
          path: ./app/requirements.txt
        - action: rebuild
          path: ./Dockerfile
